### ISSUE TITLE
Should rails-ujs be included in this documentation?

### ISSUE THREAD

**Issue by jacobdaddario** [noelrappin/rails_javascript_documention_drafts#10]
Hey there! I'm filing this issue after being directed to your thread by [this mod post](https://discuss.rubyonrails.org/t/rails-ujs-documentation/74518/7?u=jacobdaddario). I'd love to document some of the methods contained in the Rails-UJS gem, and it looks like the mod directed me here to do so.

Let me know what your thoughts are and what best to do to help with documenting some of Rails' JavaScript behavior.

**Comment by codergeek121** [comment]
Thanks for your help :)
I personally think documenting all Rails-UJS Methods in the Webpacker guide would be out of scope for the Webpacker guide. 
What would certainly fit in my opinion is how to set up Rails-UJS with Webpacker, maybe you can add a section here :)?
I actually found this comment: https://github.com/rails/rails/pull/37529#issuecomment-575344788 maybe that's a reason not all UJS methods are documented?

**Comment by jacobdaddario** [comment]
@codergeek121 
I'd be more than happy to write a section on setting-up Rails-UJS with Webpacker. Should I fork this repository and scaffold something out?

I only asked about adding in documentation at the suggestion of the moderator, I agree that it doesn't fit into the webpacker guide. That comment you mentioned in the Rails PR is interesting, as there was some discussion in the original UJS thread regarding whether the methods should even be used, and no one seemed to know for certain. I've particularly seen people recommend their use as a matter-of-fact.

I'll be sure to tag this back to the original thread on documenting Rails UJS methods.

**Comment by noelrappin** [comment]
I'm certainly open to people adding additional documents here. DHH has said that Rails-UJS is going to be either removed, deprecated or replaced once the enhancements from hey.com are pulled in, so maybe it's worth holding on for a bit before putting a ton of work into it, but I agree that there's documentation to be written outside Webpacker itself

**Comment by jacobdaddario** [comment]
Makes sense! I'm going to go ahead and close out this Issue.
